"""add_rol_plataforma_enum

Revision ID: 0d3d66258a13
Revises: 
Create Date: 2025-08-27 15:12:16.817025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d3d66258a13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('nombre'), table_name='roles')
    op.drop_table('roles')
    op.add_column('asignaciones', sa.Column('rol_musical_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'asignaciones', 'domingos', ['domingo_id'], ['id'])
    op.create_foreign_key(None, 'asignaciones', 'roles_musicales', ['rol_musical_id'], ['id'])
    op.create_foreign_key(None, 'asignaciones', 'integrantes', ['integrante_id'], ['id'])
    op.drop_column('asignaciones', 'rol_id')
    op.add_column('usuarios', sa.Column('rol_plataforma', sa.Enum('admin', 'regular', name='rolusuario'), nullable=True))
    op.add_column('usuarios', sa.Column('integrante_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'integrantes', ['integrante_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'integrante_id')
    op.drop_column('usuarios', 'rol_plataforma')
    op.add_column('asignaciones', sa.Column('rol_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asignaciones', type_='foreignkey')
    op.drop_constraint(None, 'asignaciones', type_='foreignkey')
    op.drop_constraint(None, 'asignaciones', type_='foreignkey')
    op.drop_column('asignaciones', 'rol_musical_id')
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nombre'), 'roles', ['nombre'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
